name: Cache Prime Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cache-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Python dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-91cd5c7
          restore-keys: |
            cache-

      - name: prime-cache-91cd5c7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx
